name: create a comment on new isses 

on:
  issues: 
    types: [opened]


jobs:
  comment-with-action:
    runa-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq 
        shell: bash 
